import Head from "next/head";
import {
  Button,
  Stack,
  ThemeProvider,
  Box,
  Container,
  Grid,
  Paper,
} from "@mui/material";
import theme from "@/themes";
import { Sign } from "crypto";
import { SignupForm } from "@/components/SignupForm";
import { LoginForm } from "@/components/LoginForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ThemeProvider theme={theme}>
        {/* <Stack
          sx={{
            mt: 2,
            px: 2,
            height: "100vh",
          }}
          alignItems="center"
          justifyContent="space-around"
        >
          <Box>
            <Button variant="contained">Hello World</Button>
          </Box>
          <Box>
            <Button variant="outlined">Hello World !!!</Button>
          </Box>
          <Box>
            <Button variant="contained" color="secondary">
              Hello World how are you
            </Button>
          </Box>
          <Box>
            <Button variant="outlined" color="secondary">
              Hello World good job
            </Button>
          </Box>

          <Stack
            direction="row"
            width="100%"
            spacing={2}
            justifyContent="center"
            alignItems="center"
          >
            <Box>
              <Button variant="contained">Hello World</Button>
            </Box>
            <Box>
              <Button sx={{ height: "100px" }} variant="outlined">
                Hello World
              </Button>
            </Box>
          </Stack>
        </Stack> */}

        <Container maxWidth="md">
          <SignupForm />
        </Container>
      </ThemeProvider>
    </>
  );
}
